
test_data = {
    'regression': 'regression.t',
    'regress': 'regress.p',

    'assignment': 'assignment.t',
    'binops': 'binops.t',
    'boolean': 'boolean.t',
    'boolean_var': 'boolean_var.t',
    'commands': 'commands.t',
    'constant_expr': 'constant_expr.t',
    'duration': 'duration.t',
    'empty_sets': 'empty_sets.t',
    'expressions': 'expressions.t',
    'functions': 'functions.t',
    'grouping': 'grouping.t',
    'identifiers': 'identifiers.t',
    'indexed_properties': 'indexed_properties.t',
    'indexing': 'indexing.t',
    'keywords': 'keywords.t',
    'language': 'language.t',
    'lifting': 'lifting.t',
    'lists': 'lists.t',
    'literals': 'literals.t',
    'none': 'none.t',
    'parameters': 'parameters.t',
    'properties': 'properties.t',
    'ranges' : 'ranges.t',
    'sequences': 'sequences.t',
    'set_operations': 'set_operations.t',
    'set_parameters': 'set_parameters.t',
    'set_unary': 'set_unary.t',
    'sets': 'sets.t',
    'shell': 'shell.t',
    'simple': 'simple.p',
    'simple2': 'simple2.p',
    'simpler': 'simpler.p',
    'statements': 'statements.t',
    'system1': 'system1.p',
    'system2': 'system2.p',
    'time': 'time.t',
    'trading': 'trading.t',
    'unary': 'unary.t',
}
