
test_data = {
    'regression': 'regression.t',
    'regress': 'regress.p',

    'assignment': 'assignment.t',
    'binops': 'binops.t',
    'blocks': 'blocks.t',
    'boolean': 'boolean.t',
    'boolean_var': 'boolean_var.t',
    'constant_expr': 'constant_expr.t',
    'datasets': 'datasets.f',
    'declaration': 'declaration.t',
    'declarations_multiline': 'declarations_multiline.f',
    'duration': 'duration.t',
    'empty_sets': 'empty_sets.t',
    'eval_sequences': 'eval_sequences.t',
    'eval_test': 'eval_test.p',
    'expressions': 'expressions.t',
    'factorial': 'factorial.f',
    'flow': 'flow.p',
    'flow2': 'flow2.f',
    'functions_decl': 'functions_decl.f',
    'functions_invoke': 'functions_invoke.t',
    'grouping': 'grouping.t',
    'identifiers': 'identifiers.t',
    'indexed_properties': 'indexed_properties.t',
    'indexing': 'indexing.t',
    'keywords': 'keywords.t',
    'language': 'language.t',
    'language_expr': 'language_expr.t',
    'lifting': 'lifting.t',
    'lists': 'lists.t',
    'none': 'none.t',
    'parameters': 'parameters.t',
    'prime': 'prime.t',
    'properties': 'properties.t',
    'ranges': 'ranges.t',
    'sequences': 'sequences.t',
    'series': 'series.t',
    'set_operations': 'set_operations.t',
    'set_parameters': 'set_parameters.t',
    'set_unary': 'set_unary.t',
    'sets': 'sets.t',
    'simple': 'simple.p',
    'simple2': 'simple2.p',
    'simpler': 'simpler.p',
    'slicing': 'slicing.f',
    'statements': 'statements.t',
    'system1': 'system1.p',
    'system2': 'system2.p',
    'time': 'time.t',
    'trading': 'trading.t',
    'tuples': 'tuples.t',
    'unary': 'unary.t',
    'var': 'var.t',
    # 'yahoo2': 'yahoo2.f',
}
