from runtime.token_ids import TK


# --------------------------------------------------
#                    T A B L E S 
# --------------------------------------------------
# 'any' is used to denote the generic routine instead of everything ending up appearing as an int_ conversion

# abbreviations in table:
#   l = l_value    2i: = c_to_int   2f: = c_to_float    u: = unbox      .o = l.from_object( )
#   r = r_value    2b: = c_to_bool  2d: = c_to_dur      b: = box        .b = .from_block( )
#                                                       s: = f'{ }'     .v = .value =
#
#
#   B = TK.BOOL     D = TK.DUR       F = TK.FLOT        I = TK.INT      L = TK.LIST     O = TK.OBJECT   S = TK.STR


# --------------------------------------------------
#         A S S I G N M E N T   T A B L E S 
# --------------------------------------------------
_assign_obj_fn = {
    TK.APPLY: [
        # any           none          int           float         bool          str           datetime      timedelta     object        block         dataframe     range         series        set           list          ndarray       function      
        ["b:l,u:r",    "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # any      
        ["l=r",        "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # none      
        ["l=r",        "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # int      
        ["l=r",        "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # float      
        ["l=r",        "invalid",    "l=r",        "l=r",        "invalid",    "l=r",        "invalid",    "invalid",    "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # bool      
        ["l=r",        "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # str      
        ["b:l,r",      "invalid",    "b:l,r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l.o",        "l.b",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # datetime      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l.b",        "l=r",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # timedelta      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Object      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Block      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid"],   # DataFrame      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Range      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid"],   # Series      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "invalid",    "invalid"],   # Set      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "l=r",        "invalid"],   # list      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "l=r",        "invalid"],   # ndarray      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # function      
    
        ],
    TK.ASSIGN: [
        # any           none          int           float         bool          str           datetime      timedelta     object        block         dataframe     range         series        set           list          ndarray       function      
        ["b:l,u:r",    "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # any      
        ["l=r",        "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # none      
        ["l=r",        "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # int      
        ["l=r",        "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # float      
        ["l=r",        "invalid",    "l=r",        "l=r",        "invalid",    "l=r",        "invalid",    "invalid",    "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # bool      
        ["l=r",        "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # str      
        ["b:l,r",      "invalid",    "b:l,r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l.o",        "l.b",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # datetime      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l.b",        "l=r",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # timedelta      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Object      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Block      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid"],   # DataFrame      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Range      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid"],   # Series      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "invalid",    "invalid"],   # Set      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "l=r",        "invalid"],   # list      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "l=r",        "invalid"],   # ndarray      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # function      
    
        ],
    TK.DEFINE: [
        # any           none          int           float         bool          str           datetime      timedelta     object        block         dataframe     range         series        set           list          ndarray       function      
        ["b:l,u:r",    "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # any      
        ["l=r",        "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # none      
        ["l=r",        "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # int      
        ["l=r",        "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # float      
        ["l=r",        "invalid",    "l=r",        "l=r",        "invalid",    "l=r",        "invalid",    "invalid",    "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # bool      
        ["l=r",        "invalid",    "invalid",    "l=r",        "l=r",        "l=r",        "l=r",        "l=r",        "b:l,u:r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # str      
        ["b:l,r",      "invalid",    "b:l,r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l.o",        "l.b",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # datetime      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l.b",        "l=r",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # timedelta      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Object      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Block      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid"],   # DataFrame      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Range      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "invalid",    "invalid",    "invalid"],   # Series      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "invalid",    "invalid",    "invalid"],   # Set      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "l=r",        "invalid"],   # list      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l=r",        "l=r",        "invalid"],   # ndarray      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # function      
    
        ],
}


# --------------------------------------------------
#         B I N A R Y   O P E R A T I O N S 
# --------------------------------------------------
_evaluate_binops_fn = {
    TK.INDEX: [
        # any           none          int           float         bool          str           datetime      timedelta     object        block         dataframe     range         series        set           list          ndarray       function      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # any      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # none      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # int      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # float      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # bool      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # str      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # datetime      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # timedelta      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Object      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Block      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # DataFrame      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Range      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Series      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Set      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # list      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # ndarray      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # function      
    
        ],
    TK.ADD: [
        # any           none          int           float         bool          str           datetime      timedelta     object        block         dataframe     range         series        set           list          ndarray       function      
        ["l + r",      "invalid",    "l + r",      "l + r",      "l + r",      "l + s:r",    "l + r",      "l + r",      "l + r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # any      
        ["l + r",      "invalid",    "l + r",      "l + r",      "l + r",      "l + s:r",    "l + r",      "l + r",      "l + r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # none      
        ["l + r",      "invalid",    "l + r",      "l + r",      "l + r",      "l + s:r",    "l + r",      "l + r",      "u:l + r",    "invalid",    "add_dfi",    "invalid",    "add_si",     "invalid",    "add_li",     "add_li",     "invalid"],   # int      
        ["l + r",      "invalid",    "l + r",      "l + r",      "l + r",      "l + s:r",    "l + r",      "l + r",      "u:l + r",    "invalid",    "add_dfi",    "invalid",    "add_si",     "invalid",    "add_li",     "add_li",     "invalid"],   # float      
        ["l + r",      "invalid",    "l + r",      "l + r",      "l + r",      "l + s:r",    "l + r",      "l + r",      "u:l + r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # bool      
        ["s:l + r",    "invalid",    "l + r",      "l + r",      "s:l + r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # str      
        ["l + r",      "invalid",    "l + r",      "l + r",      "l + r",      "l + s:r",    "l + r",      "l + r",      "u:l + r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # datetime      
        ["l + r",      "invalid",    "l + r",      "l + r",      "l + r",      "l + s:r",    "l + r",      "l + r",      "u:l + r",    "invalid",    "add_dftd",   "invalid",    "add_tds",    "invalid",    "add_tdl",    "add_tdl",    "invalid"],   # timedelta      
        ["l + r",      "invalid",    "l + u:r",    "l + r",      "l + r",      "l + s:r",    "l + r",      "l + r",      "l + r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Object      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Block      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "add_dfdf",   "invalid",    "sadd(l,r)",  "invalid",    "add_ldf",    "add_ldf",    "invalid"],   # DataFrame      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "add_rr",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Range      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "add_dfs",    "invalid",    "add_ss",     "invalid",    "add_ls",     "add_ls",     "invalid"],   # Series      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "add_stst",   "invalid",    "invalid",    "invalid"],   # Set      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "add_sfl",    "invalid",    "add_sl",     "invalid",    "add_ll",     "add_ll",     "invalid"],   # list      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "add_dfl",    "invalid",    "add_sl",     "invalid",    "add_ll",     "add_ll",     "invalid"],   # ndarray      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # function      
    
        ],
    TK.SUB: [
        # any           none          int           float         bool          str           datetime      timedelta     object        block         dataframe     range         series        set           list          ndarray       function      
        ["l - r",      "invalid",    "l - r",      "l - r",      "l - r",      "invalid",    "l - r",      "l - r",      "l - r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # any      
        ["l - r",      "invalid",    "l - r",      "l - r",      "l - r",      "invalid",    "l - r",      "l - r",      "l - r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # none      
        ["l - r",      "invalid",    "l - r",      "l - r",      "l - r",      "invalid",    "l - r",      "l - r",      "u:l - r",    "invalid",    "sub_dfi",    "invalid",    "sub_si",     "invalid",    "sub_li",     "sub_li",     "invalid"],   # int      
        ["l - r",      "invalid",    "l - r",      "l - r",      "l - r",      "invalid",    "l - r",      "l - r",      "u:l - r",    "invalid",    "sub_dfi",    "invalid",    "sub_si",     "invalid",    "sub_li",     "sub_li",     "invalid"],   # float      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l - r",      "l - r",      "l - r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # bool      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l - r",      "l - r",      "l - r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # str      
        ["l - r",      "invalid",    "l - r",      "l - r",      "l - r",      "invalid",    "l - r",      "l - r",      "u:l - r",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # datetime      
        ["l - r",      "invalid",    "l - r",      "l - r",      "l - r",      "invalid",    "l - r",      "l - r",      "u:l - r",    "invalid",    "sub_dftd",   "invalid",    "sub_std",    "invalid",    "invalid",    "invalid",    "invalid"],   # timedelta      
        ["l - r",      "invalid",    "l - u:r",    "l - r",      "l - r",      "invalid",    "l - r",      "l - r",      "l - r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Object      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Block      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "sub_dfdf",   "invalid",    "ssub(l,r)",  "invalid",    "invalid",    "invalid",    "invalid"],   # DataFrame      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "sub_rr",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Range      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "sub_ss",     "invalid",    "invalid",    "invalid",    "invalid"],   # Series      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "sub_stst",   "invalid",    "invalid",    "invalid"],   # Set      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "sub_ll",     "sub_ll",     "invalid"],   # list      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "sub_ll",     "sub_ll",     "invalid"],   # ndarray      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # function      
    
        ],
    TK.DIV: [
        # any           none          int           float         bool          str           datetime      timedelta     object        block         dataframe     range         series        set           list          ndarray       function      
        ["l / r",      "invalid",    "l / r",      "l / r",      "l / r",      "invalid",    "l / r",      "l / r",      "l / r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # any      
        ["l / r",      "invalid",    "l / r",      "l / r",      "l / r",      "invalid",    "l / r",      "l / r",      "l / r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # none      
        ["l / r",      "invalid",    "l / r",      "l / r",      "l / r",      "invalid",    "l / r",      "l / r",      "u:l / r",    "invalid",    "div_dfi",    "invalid",    "div_si",     "invalid",    "div_li",     "div_li",     "invalid"],   # int      
        ["l / r",      "invalid",    "l / r",      "l / r",      "l / r",      "invalid",    "l / r",      "l / r",      "u:l / r",    "invalid",    "div_dfi",    "invalid",    "div_si",     "invalid",    "div_li",     "div_li",     "invalid"],   # float      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l / r",      "l / r",      "l / r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # bool      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l / r",      "l / r",      "l / r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # str      
        ["l / r",      "invalid",    "l / r",      "l / r",      "l / r",      "invalid",    "l / r",      "l / r",      "l / r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # datetime      
        ["l / r",      "invalid",    "l / r",      "l / r",      "l / r",      "invalid",    "l / r",      "l / r",      "l / r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # timedelta      
        ["l / r",      "invalid",    "l / u:r",    "l / r",      "l / r",      "invalid",    "l / r",      "l / r",      "l / r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Object      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Block      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "div_dfdf",   "invalid",    "sdiv(l,r)",  "invalid",    "invalid",    "invalid",    "invalid"],   # DataFrame      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "div_rr",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Range      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "div_ss",     "invalid",    "invalid",    "invalid",    "invalid"],   # Series      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "div_stst",   "invalid",    "invalid",    "invalid"],   # Set      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "div_ll",     "div_ll",     "invalid"],   # list      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "div_ll",     "div_ll",     "invalid"],   # ndarray      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # function      
    
        ],
    TK.IDIV: [
        # any           none          int           float         bool          str           datetime      timedelta     object        block         dataframe     range         series        set           list          ndarray       function      
        ["l // r",     "invalid",    "l // r",     "l // r",     "l // r",     "invalid",    "l // r",     "l // r",     "l // r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # any      
        ["l // r",     "invalid",    "l // r",     "l // r",     "l // r",     "invalid",    "l // r",     "l // r",     "l // r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # none      
        ["l // r",     "invalid",    "l // r",     "l // r",     "l // r",     "invalid",    "l // r",     "l // r",     "u:l // r",   "invalid",    "idiv_dfi",   "invalid",    "idiv_si",    "invalid",    "idiv_li",    "idiv_li",    "invalid"],   # int      
        ["l // r",     "invalid",    "l // r",     "l // r",     "l // r",     "invalid",    "l // r",     "l // r",     "u:l // r",   "invalid",    "idiv_dfi",   "invalid",    "idiv_si",    "invalid",    "idiv_li",    "idiv_li",    "invalid"],   # float      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l // r",     "l // r",     "l // r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # bool      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l // r",     "l // r",     "l // r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # str      
        ["l // r",     "invalid",    "l // r",     "l // r",     "l // r",     "invalid",    "l // r",     "l // r",     "l // r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # datetime      
        ["l // r",     "invalid",    "l // r",     "l // r",     "l // r",     "invalid",    "l // r",     "l // r",     "l // r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # timedelta      
        ["l // r",     "invalid",    "l // u:r",   "l // r",     "l // r",     "invalid",    "l // r",     "l // r",     "l // r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Object      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Block      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "idiv_dfdf",  "invalid",    "sidiv(l,r)", "invalid",    "invalid",    "invalid",    "invalid"],   # DataFrame      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "idiv_rr",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Range      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "idiv_ss",    "invalid",    "invalid",    "invalid",    "invalid"],   # Series      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "idiv_ss",    "invalid",    "invalid",    "invalid"],   # Set      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "idiv_ll",    "idiv_ll",    "invalid"],   # list      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "idiv_ll",    "idiv_ll",    "invalid"],   # ndarray      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # function      
    
        ],
    TK.POW: [
        # any           none          int           float         bool          str           datetime      timedelta     object        block         dataframe     range         series        set           list          ndarray       function      
        ["l ** r",     "invalid",    "l ** r",     "l ** r",     "l ** r",     "invalid",    "l ** r",     "l ** r",     "l ** r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # any      
        ["l ** r",     "invalid",    "l ** r",     "l ** r",     "l ** r",     "invalid",    "l ** r",     "l ** r",     "l ** r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # none      
        ["l ** r",     "invalid",    "l ** r",     "l ** r",     "l ** r",     "invalid",    "l ** r",     "l ** r",     "u:l ** r",   "invalid",    "pow_dfi",    "invalid",    "pow_si",     "invalid",    "pow_li",     "pow_li",     "invalid"],   # int      
        ["l ** r",     "invalid",    "l ** r",     "l ** r",     "l ** r",     "invalid",    "l ** r",     "l ** r",     "u:l ** r",   "invalid",    "pow_dfi",    "invalid",    "pow_so",     "invalid",    "pow_li",     "pow_li",     "invalid"],   # float      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l ** r",     "l ** r",     "l ** r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # bool      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "l ** r",     "l ** r",     "l ** r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # str      
        ["l ** r",     "invalid",    "l ** r",     "l ** r",     "l ** r",     "invalid",    "l ** r",     "l ** r",     "l ** r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # datetime      
        ["l ** r",     "invalid",    "l ** r",     "l ** r",     "l ** r",     "invalid",    "l ** r",     "l ** r",     "l ** r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # timedelta      
        ["l ** r",     "invalid",    "l ** u:r",   "l ** r",     "l ** r",     "invalid",    "l ** r",     "l ** r",     "l ** r",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Object      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Block      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "pow_dfdf",   "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # DataFrame      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "pow_rr",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Range      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "pow_ss",     "invalid",    "invalid",    "invalid",    "invalid"],   # Series      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "pow_stst",   "invalid",    "invalid",    "invalid"],   # Set      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "pow_ll",     "pow_ll",     "invalid"],   # list      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "pow_ll",     "pow_ll",     "invalid"],   # ndarray      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # function      
    
        ],
    TK.MUL: [
        # any           none          int           float         bool          str           datetime      timedelta     object        block         dataframe     range         series        set           list          ndarray       function      
        ["l * r",      "invalid",    "l * r",      "l * r",      "l * r",      "l * r",      "l * r",      "l * r",      "l * r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # any      
        ["l * r",      "invalid",    "l * r",      "l * r",      "l * r",      "l * r",      "l * r",      "l * r",      "l * r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # none      
        ["l * r",      "invalid",    "l * r",      "l * r",      "l * r",      "l * r",      "l * r",      "l * r",      "u:l * r",    "invalid",    "mul_dfi",    "invalid",    "mul_si",     "invalid",    "mul_li",     "mul_li",     "invalid"],   # int      
        ["l * r",      "invalid",    "l * r",      "l * r",      "l * r",      "l * r",      "l * r",      "l * r",      "u:l * r",    "invalid",    "mul_dfi",    "invalid",    "mul_si",     "invalid",    "mul_li",     "mul_li",     "invalid"],   # float      
        ["l * r",      "invalid",    "l * r",      "l * r",      "l * r",      "invalid",    "l * r",      "l * r",      "l * r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # bool      
        ["l * r",      "invalid",    "l * r",      "l * r",      "l * r",      "invalid",    "l * r",      "l * r",      "l * r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # str      
        ["l * r",      "invalid",    "l * r",      "l * r",      "l * r",      "invalid",    "l * r",      "l * r",      "l * r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # datetime      
        ["l * r",      "invalid",    "l * r",      "l * r",      "l * r",      "invalid",    "l * r",      "l * r",      "l * r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # timedelta      
        ["l * r",      "invalid",    "l * u:r",    "l * r",      "l * r",      "invalid",    "l * r",      "l * r",      "l * r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Object      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "lrmul(l,r)", "invalid",    "invalid",    "invalid",    "invalid"],   # Block      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "mul_dfdf",   "invalid",    "smul(l,r)",  "invalid",    "invalid",    "invalid",    "invalid"],   # DataFrame      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "mul_rr",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Range      
        ["invalid",    "invalid",    "i:*l",       "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "mul_ss",     "invalid",    "invalid",    "invalid",    "invalid"],   # Series      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "mul_stst",   "invalid",    "invalid",    "invalid"],   # Set      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "mul_ll",     "mul_ll",     "invalid"],   # list      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "mul_ll",     "mul_ll",     "invalid"],   # ndarray      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # function      
    
        ],
    TK.MOD: [
        # any           none          int           float         bool          str           datetime      timedelta     object        block         dataframe     range         series        set           list          ndarray       function      
        ["l % r",      "invalid",    "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # any      
        ["l % r",      "invalid",    "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # none      
        ["l % r",      "invalid",    "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "u:l % r",    "invalid",    "mod_si",     "invalid",    "mod_si",     "invalid",    "mod_li",     "mod_li",     "invalid"],   # int      
        ["l % r",      "invalid",    "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "u:l % r",    "invalid",    "mod_si",     "invalid",    "mod_si",     "invalid",    "mod_li",     "mod_li",     "invalid"],   # float      
        ["l % r",      "invalid",    "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # bool      
        ["l % r",      "invalid",    "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # str      
        ["l % r",      "invalid",    "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # datetime      
        ["l % r",      "invalid",    "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # timedelta      
        ["l % r",      "invalid",    "l % u:r",    "l % r",      "l % r",      "l % r",      "l % r",      "l % r",      "u:l % u:r",  "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Object      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Block      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "mod_dfdf",   "invalid",    "smod(l,r)",  "invalid",    "invalid",    "invalid",    "invalid"],   # DataFrame      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "mod_rr",     "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # Range      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "mod_ss",     "invalid",    "invalid",    "invalid",    "invalid"],   # Series      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "mod_stst",   "invalid",    "invalid",    "invalid"],   # Set      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "mod_ll",     "mod_ll",     "invalid"],   # list      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "mod_ll",     "mod_ll",     "invalid"],   # ndarray      
        ["invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid",    "invalid"],   # function      
    
        ],
}


# --------------------------------------------------
#        B O O L E A N   O P E R A T I O N S 
# --------------------------------------------------
_evaluate_boolops_fn = {
    TK.AND: [
        # any             none            int             float           bool            str             datetime        timedelta       object          block           dataframe       range           series          set             list            ndarray         function        
        ["l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # any      
        ["l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # none      
        ["l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # int      
        ["l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # float      
        ["l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # bool      
        ["l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "l and r",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # str      
        ["X",            "X",            "X",            "X",            "X",            "X",            "X",            "X",            "X",            "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # datetime      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "and_tdtd",     "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # timedelta      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "and_oo",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Object      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Block      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_and_df",    "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # DataFrame      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "and_rr",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Range      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "and_ss",       "invalid",      "invalid",      "invalid",      "invalid"],   # Series      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "and_stst",     "invalid",      "invalid",      "invalid"],   # Set      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "and_ll",       "and_ll",       "invalid"],   # list      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "and_ll",       "and_ll",       "invalid"],   # ndarray      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # function      
    
        ],
    TK.OR: [
        # any             none            int             float           bool            str             datetime        timedelta       object          block           dataframe       range           series          set             list            ndarray         function        
        ["l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # any      
        ["l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # none      
        ["l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # int      
        ["l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # float      
        ["l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # bool      
        ["l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # str      
        ["l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "l or r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # datetime      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "or_oo",        "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # timedelta      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Object      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Block      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_or_df",     "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # DataFrame      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Range      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "or_ss",        "invalid",      "invalid",      "invalid",      "invalid"],   # Series      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "or_stst",      "invalid",      "invalid",      "invalid"],   # Set      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "or_ll",        "or_ll",        "invalid"],   # list      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "or_ll",        "or_ll",        "invalid"],   # ndarray      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # function      
    
        ],
    TK.ISEQ: [
        # any             none            int             float           bool            str             datetime        timedelta       object          block           dataframe       range           series          set             list            ndarray         function        
        ["l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "invalid",      "pd_eq_dfr",    "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # any      
        ["l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # none      
        ["l == r",       "l == r",       "l == r",       "l == r",       "2f:l == r",    "2f:l == r",    "l == r",       "l == r",       "l == r",       "invalid",      "pd_eq_dfr",    "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # int      
        ["l == r",       "l == r",       "l == 2i:r",    "l == 2f:r",    "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "invalid",      "pd_eq_dfr",    "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # float      
        ["l == 2i:r",    "l == 2i:r",    "l == 2i:r",    "l == 2f:r",    "l == 2b:r",    "l == r",       "l == 2d:r",    "l == 2d:r",    "l == r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # bool      
        ["l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # str      
        ["l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # datetime      
        ["l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "l == r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # timedelta      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "ideq_oo",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Object      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Block      
        ["pd_eq_df",     "invalid",      "pd_eq_df",     "pd_eq_df",     "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_eq_df",     "invalid",      "pd_eq_df",     "invalid",      "invalid",      "invalid",      "invalid"],   # DataFrame      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "iseq_rr",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Range      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_eq_dfr",    "invalid",      "iseq_ss",      "invalid",      "invalid",      "invalid",      "invalid"],   # Series      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "iseq_stst",    "invalid",      "invalid",      "invalid"],   # Set      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "iseq_ll",      "iseq_ll",      "invalid"],   # list      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "iseq_ll",      "iseq_ll",      "invalid"],   # ndarray      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # function      
    
        ],
    TK.NEQ: [
        # any             none            int             float           bool            str             datetime        timedelta       object          block           dataframe       range           series          set             list            ndarray         function        
        ["l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "invalid",      "pd_neq_dfr",   "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # any      
        ["l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # none      
        ["l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "invalid",      "pd_neq_dfr",   "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # int      
        ["l != r",       "l != r",       "l != 2i:r",    "l != 2i:r",    "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "invalid",      "pd_neq_dfr",   "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # float      
        ["l != 2i:r",    "l != 2i:r",    "l != 2i:r",    "l != 2f:r",    "l != 2b:r",    "l != r",       "l != 2d:r",    "l != 2d:r",    "l != r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # bool      
        ["l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # str      
        ["l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # datetime      
        ["l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "l != r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # timedelta      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "neq_oo",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Object      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Block      
        ["pd_neq_df",    "invalid",      "pd_neq_df",    "pd_neq_df",    "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_neq_df",    "invalid",      "pd_neq_df",    "invalid",      "invalid",      "invalid",      "invalid"],   # DataFrame      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "neq_rr",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Range      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_neq_dfr",   "invalid",      "neq_ss",       "invalid",      "invalid",      "invalid",      "invalid"],   # Series      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "meq_stst",     "invalid",      "invalid",      "invalid"],   # Set      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "neq_ll",       "neq_ll",       "invalid"],   # list      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "neq_ll",       "neq_ll",       "invalid"],   # ndarray      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # function      
    
        ],
    TK.GTR: [
        # any             none            int             float           bool            str             datetime        timedelta       object          block           dataframe       range           series          set             list            ndarray         function        
        ["l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "invalid",      "pd_gtr_dfr",   "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # any      
        ["l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # none      
        ["l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "invalid",      "pd_gtr_dfr",   "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # int      
        ["l > r",        "l > r",        "l > 2i:r",     "l > 2i:r",     "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "invalid",      "pd_gtr_dfr",   "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # float      
        ["l > 2i:r",     "l > 2i:r",     "l > 2i:r",     "l > 2f:r",     "l > 2b:r",     "l > r",        "l > 2d:r",     "l > 2d:r",     "l > r",        "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # bool      
        ["l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # str      
        ["l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # datetime      
        ["l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "l > r",        "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # timedelta      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "isgt_oo",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Object      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Block      
        ["pd_gtr_df",    "invalid",      "pd_gtr_df",    "pd_gtr_df",    "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_gtr_df",    "invalid",      "pd_gtr_df",    "invalid",      "invalid",      "invalid",      "invalid"],   # DataFrame      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "isgt_rr",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Range      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_gtr_dfr",   "invalid",      "isgt_ss",      "invalid",      "invalid",      "invalid",      "invalid"],   # Series      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "isgt_stst",    "invalid",      "invalid",      "invalid"],   # Set      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "isgt_ll",      "isgt_ll",      "invalid"],   # list      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "isgt_ll",      "isgt_ll",      "invalid"],   # ndarray      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # function      
    
        ],
    TK.LESS: [
        # any             none            int             float           bool            str             datetime        timedelta       object          block           dataframe       range           series          set             list            ndarray         function        
        ["l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "invalid",      "pd_less_dfr",  "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # any      
        ["l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # none      
        ["l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "invalid",      "pd_less_dfr",  "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # int      
        ["l < r",        "l < r",        "l < 2i:r",     "l < 2i:r",     "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "invalid",      "pd_less_dfr",  "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # float      
        ["l < 2i:r",     "l < 2i:r",     "l < 2i:r",     "l < 2f:r",     "l < 2b:r",     "l < r",        "l < 2d:r",     "l < 2d:r",     "l < r",        "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # bool      
        ["l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # str      
        ["l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # datetime      
        ["l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "l < r",        "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # timedelta      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "islt_oo",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Object      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Block      
        ["pd_less_df",   "invalid",      "pd_less_df",   "pd_less_df",   "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_less_df",   "invalid",      "pd_less_df",   "invalid",      "invalid",      "invalid",      "invalid"],   # DataFrame      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "islt_rr",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Range      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_less_dfr",  "invalid",      "islt_stst",    "invalid",      "invalid",      "invalid",      "invalid"],   # Series      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "islt_ss",      "invalid",      "invalid",      "invalid"],   # Set      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "islt_ll",      "islt_ll",      "invalid"],   # list      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "islt_ll",      "islt_ll",      "invalid"],   # ndarray      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # function      
    
        ],
    TK.GTE: [
        # any             none            int             float           bool            str             datetime        timedelta       object          block           dataframe       range           series          set             list            ndarray         function        
        ["l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "invalid",      "pd_gte_dfr",   "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # any      
        ["l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # none      
        ["l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "invalid",      "pd_gte_dfr",   "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # int      
        ["l >= r",       "l >= r",       "l >= 2i:r",    "l >= 2i:r",    "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "invalid",      "pd_gte_dfr",   "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # float      
        ["l >= 2i:r",    "l >= 2i:r",    "l >= 2i:r",    "l >= 2f:r",    "l >= 2b:r",    "l >= r",       "l >= 2d:r",    "l >= 2d:r",    "l >= r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # bool      
        ["l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # str      
        ["l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # datetime      
        ["l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "l >= r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # timedelta      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "isgte_oo",     "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Object      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Block      
        ["pd_gte_df",    "invalid",      "pd_gte_df",    "pd_gte_df",    "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_gte_df",    "invalid",      "pd_gte_df",    "invalid",      "invalid",      "invalid",      "invalid"],   # DataFrame      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "isgte_rr",     "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Range      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_gte_dfr",   "invalid",      "isgte_ss",     "invalid",      "invalid",      "invalid",      "invalid"],   # Series      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "is_lte_stst",  "invalid",      "invalid",      "invalid"],   # Set      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "isgte_ll",     "isgte_ll",     "invalid"],   # list      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "isgte_ll",     "isgte_ll",     "invalid"],   # ndarray      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # function      
    
        ],
    TK.LTE: [
        # any             none            int             float           bool            str             datetime        timedelta       object          block           dataframe       range           series          set             list            ndarray         function        
        ["l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "invalid",      "pd_lte_dfr",   "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # any      
        ["l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # none      
        ["l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "invalid",      "pd_lte_dfr",   "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # int      
        ["l <= r",       "l <= r",       "l <= 2i:r",    "l <= 2i:r",    "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "invalid",      "pd_lte_dfr",   "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # float      
        ["l <= 2i:r",    "l <= 2i:r",    "l <= 2i:r",    "l <= 2f:r",    "l <= 2b:r",    "l <= r",       "l <= 2d:r",    "l <= 2d:r",    "l <= r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # bool      
        ["l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # str      
        ["l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # datetime      
        ["l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "l <= r",       "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # timedelta      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "isgte_oo",     "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Object      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Block      
        ["pd_lte_df",    "invalid",      "pd_lte_df",    "pd_lte_df",    "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_lte_df",    "invalid",      "pd_lte_df",    "invalid",      "invalid",      "invalid",      "invalid"],   # DataFrame      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "islte_rr",     "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # Range      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "pd_lte_dfr",   "invalid",      "islte_ss",     "invalid",      "invalid",      "invalid",      "invalid"],   # Series      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "is_lte_stst",  "invalid",      "invalid",      "invalid"],   # Set      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "islte_ll",     "islte_ll",     "invalid"],   # list      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "islte_ll",     "islte_ll",     "invalid"],   # ndarray      
        ["invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid",      "invalid"],   # function      
    
        ],
}
