a = 4
a = 2 * 3
a = b
a = b = c
a = b.c(x,y,z)
(a = 5)
{a = 5}
# :(a = 5) - syntax error
a += 1
b -= 2
a := 3
trade_size := position * 10%
report := { trades | select('symbol', 'buy_date', 'buy_price', 'sell_date', 'sell_price') }
report := ( trades | select('symbol', 'buy_date', 'buy_price', 'sell_date', 'sell_price') )
s.a = 5
a().b.c = 4
a.b().c = 2
a.b.c.d() = 1
a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.x.y.z = 5
