set_operations_tests = [
    # "{a} U {b}",
    # "{a} n {b}",
    "{a} + {b}",
    "{a} - {b}",
    "{a} and {b}",
    "{a} or {b}",
    "{a} | {b}",
    "{a} & {b}",
    "{a} ^ {b}",
    "{a} >> {b}",
    "{a} . {b}",
    "{a} * {b}",
    "{a, b}",
    "not {b}",
    "not {a, b}",
]